app/home/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/11/25 上午5:58
# @Author  : Aries
# @File    : forms.py
# @Software: PyCharm
# @Email   : dewujie64@gmail.com
import re

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from app.models import User, Admin

class LoginForm(FlaskForm):
    account = StringField(label='帐号', validators=[DataRequired('请输入用户名')], description='帐号',
                          render_kw={
                              'placeholder': "请输入账号！",
                              'required': 'required'
                          })
    pwd = PasswordField(label='密码', validators=[DataRequired('请输入密码')], description='密码',
                          render_kw={
                              'placeholder': "请输入密码！",
                              'required': 'required'
                          })
    submit = SubmitField(label='登录',render_kw={'required': 'required'})

    def validate_account(self,field):
        account = field.data
        user = User.query.filter_by(name=account).count()
        if user == 0:
            raise ValidationError('帐号不存在')

class SignupForm(FlaskForm):
    username = StringField(label='用户名', validators=[DataRequired('请输入用户名')], description='用户名',
                          render_kw={
                              'placeholder': "请输入用户名，不能为中文！",
                              'required': 'required'
                          })
    code = StringField(label='邀请吗', validators=[DataRequired('请输入邀请码')], description='邀请码',
                        render_kw={
                            'placeholder': "请输入邀请码！",
                            'required': 'required'
                        })
    email = StringField(label='邮箱', validators=[DataRequired('请输入邮箱')], description='邮箱',
                        render_kw={
                            'placeholder': "请输入邮箱地址！",
                            'required': 'required'
                        })
    pwd = PasswordField(label='密码', validators=[DataRequired('请输入密码')], description='密码',
                        render_kw={
                            'placeholder': "请输入密码！",
                            'required': 'required'
                        })

    pwd2 = PasswordField(label='密码', validators=[DataRequired('请输入密码')], description='密码',
                          render_kw={
                              'placeholder': "请输入密码！",
                              'required': 'required'
                          })
    submit = SubmitField(label='登录',render_kw={'required': 'required'})
    a = None
    ll = ['12345']

    def validate_username(self,field):
        username = field.data
        user = User.query.filter_by(name=username).count()
        if user != 0:
            raise ValidationError('帐号已存在')

    def validate_code(self,field):
        code = field.data
        if code not in self.ll:
            raise ValidationError('请按照下方方式正确获取邀请吗')

    def validate_email(self,field):
        email = field.data
        if not re.match(u'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            raise ValidationError('请输入正确的邮箱格式:')

    def validate_pwd(self,fiedl):
        pwd = fiedl.data
        self.a = pwd

    def validate_pwd2(self,field):
        pwd2 = field.data
        if self.a != pwd2:
            raise ValidationError('两次密码不相同:')

app/home/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/11/25 上午5:57
# @Author  : Aries
# @File    : __init__.py.py
# @Software: PyCharm
# @Email   : dewujie64@gmail.com
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019/11/25 上午5:57
# @Author  : Aries
# @File    : views.py
# @Software: PyCharm
# @Email   : dewujie64@gmail.com
import re
from functools import wraps

from werkzeug.security import generate_password_hash

from app.home.forms import LoginForm, SignupForm
from app.models import User
from . import home
from flask import render_template, redirect, url_for, request, session, flash
from app import app,db



def admin_lonin_req(f):
    @wraps(f)
    def decorated_func(*args, **kwargs):
        if not session.get('admin') or session.get('admin') == None:
            return redirect(url_for("home.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_func


@home.route("/")
@admin_lonin_req
def index():
    '''
    首页
    '''
    if not session.get('admin') or session.get('admin') == None:
        return redirect(url_for("home.login", next=request.url))
    else:
        logged_in = 1
    return render_template("home/index.html",logged_in=logged_in)


@home.route("/login/", methods=["GET", "POST"])
def login():
    '''
    登录页
    '''
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['account']).first()
        if not user.check_pwd(data['pwd']):
            flash('密码错误')
            return redirect(url_for("home.login"))
        session['admin'] = data['account']
        return redirect(request.args.get(next) or url_for("home.index"))
    return render_template('home/login.html', form=form)


@home.route("/logout/")
@admin_lonin_req
def logout():
    '''
    退出
    '''
    session.clear()
    return redirect(url_for("home.login"))


@home.route("/signup/", methods=['GET', 'POST'])
def signup():
    # 注册
    # 接收
    form = SignupForm()
    if form.validate_on_submit():
        data = form.data
        user = User(email=data['email'], pwd=generate_password_hash(data['pwd']), name=data['username'],uuid=data['code'] )
        db.session.add(user)
        db.session.commit()
        return redirect(request.args.get(next) or url_for("home.login"))
    return render_template('home/signup.html', form=form)

@home.route("/zfbzf/")
def zfbzf():
    return render_template("home/zfbzf.html")


@home.route("/wxzf/")
def wxzf():
    return render_template("home/wxzf.html")


@home.route("/wxfriend/")
def wxfriend():
    return render_template("home/wxfriend.html")


@home.route("/pwd/")
@admin_lonin_req
def pwd():
    """
    密码重置
    """
    return render_template("home/pwd.html")


#
@home.route("/moviecol/")
@admin_lonin_req
def moviecol():
    return render_template("home/moviecol.html")


@home.route("/play/")
@admin_lonin_req
def play():
    return render_template("home/video.html")

app/templates/home/account_delete_confirm.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Delete Account</title>
  <link rel="stylesheet" href="http://127.0.0.1:8080/css/reset-min.css">
  <link rel='stylesheet prefetch' href='http://127.0.0.1:8080/css/roboto.css'>
  <link rel='stylesheet prefetch' href='http://127.0.0.1:8080/css/monsterrat.css'>
  <link rel='stylesheet prefetch' href='http://127.0.0.1:8080/css/font-awesome.css'>
  <link rel="stylesheet" href="http://127.0.0.1:8080/css/style.css">
  <link rel="stylesheet" href="http://127.0.0.1:8080/css/alert.css">
  <link rel="icon" href="http://127.0.0.1:8080/favicon.png" type="image/png">
</head>

<body>
    <div class="container">
      <div class="info">
        <h1 style="color:#16A085;">Re-enter password to confirm account deletion</h1>
      </div>
    </div>
    <div class="form">
      <form class="login-form" action="delete" method="post">
        {% if c_error %}
          <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            Invalid password
          </div>
        {% endif %}
        <input id="password" type="password" name="password" placeholder="re-enter password" required autofocus/>
        <button>confirm</button>
        <a href="{{ url_for('dashboard') }}">
          <button onclick="cancel()">cancel</button>
        </a>
      </form>
    </div>
    <script src='http://127.0.0.1:8080/js/jquery.js'></script>
    <script  src="http://127.0.0.1:8080/js/delete.js"></script>
</body>
</html>

app/templates/home/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>VideoHub</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-min-337.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/png">
  </head>
  <body class="back">
    <nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="container-fluid">
       <div class="navbar-header">
         <a style="color: #16A085;" class="navbar-brand" href="{{ url_for('home.index') }}">黄星</a>
       </div>
       <form class="ml navbar-form navbar-left" action="search" method="post">
          <div class="form-group">
            <input style="width:500px;" name="search" type="text" class="form-control" placeholder="输入关键字">
          </div>
          <button type="submit" class="bt btn btn-default">搜索</button>
       </form>
       <ul class="nav navbar-nav navbar-right">
       {% if not logged_in %}
         <li><a style="color: #16A085;" href="{{ url_for('home.signup') }}">注册</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('home.login') }}">登录</a></li>
       {% endif %}
       {% if logged_in %}
         <li><a style="color: #16A085;" href="">定制</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('home.pwd') }}">密码</a></li>
         <li><a style="color: #16A085;" href="">喜欢</a></li>
         <li><a style="color: #16A085;" href="">历史</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('home.logout') }}">退出</a></li>
       {% endif %}
     </ul>
     </div>
    </nav>
    <br><br><br>
    <div class="container">
        {% block content %}
        {% endblock %}

    </div>
  </body>
</html>

app/templates/home/list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>VideoHub</title>
  </head>
  <body>
    {% for i in lista %}
      <a href="{{ url_for('watch_video', v = i[:-4]) }}">{{ lista[i] }}</a><br>
    {% endfor %}
    <form action="/search" method="post">
      Search<input type="text" name="search"><br>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

app/templates/home/loginlog.html
{% extends "home/user.html" %}
{% block content %}
<div class="twelve wide column">
    <div class="v-settings-content">
        <form novalidate="" class="ui form" method="post">

            日志

        </form>

    </div>
</div>

{% endblock %}

app/templates/home/moviecol.html
{% extends "home/user.html" %}
{% block content %}
<div class="twelve wide column">
    <div class="v-settings-content">
        <form novalidate="" class="ui form" method="post">

            收藏列表

        </form>

    </div>
</div>

{% endblock %}

app/templates/home/pwd.html
{% extends "home/home.html" %}
{% block content %}
<br>
<br>
<br>

    <div class="container">
      <div class="info">
        <h1 style="color:#16A085;">请输入原密码来更新密码</h1>
      </div>
    </div>
    <div class="form">
      <form class="login-form" action="change-password" method="post">
        {% if update_error %}
          <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            Old password does not match
          </div>
        {% endif %}
        <input type="password" name="oldPassword" placeholder="原密码" required autofocus/>
        <input type="password" name="newPassword" placeholder="新密码" required/>
        <button>提交</button>
      </form>
    </div>
{% endblock %}

app/templates/home/signup.html
{% extends "home/home.html" %}
{% block content %}
<br>
<br>
<br>
<div class="ui middle aligned center aligned grid">
    <div class="column v-account">
        <h2 class="ui teal image header">
            <div class="content" style="color: #16A085;">
                注册账户
            </div>
        </h2>
        <form class="ui large form" novalidate method="post" action="{{ url_for('home.signup') }}"
              enctype="multipart/form-data">

            {% for msg in get_flashed_messages() %}
            <div class="alert">
                <span class="closebtn" onclick="this.parentElement.style.display='none';" style="color: red">X</span>
                <a style="color: red">{{ msg }}</a>
            </div>
            {% endfor %}
            <input type="hidden" name="csrfmiddlewaretoken"
                   value="iLkQh4D5XRa67ZVPz4BVtbtJZjmSVDjuJLs9v7IEw62PolkDB5N0vIvEABDyCVKR">
            <div class="ui stacked segment">
                <div class="field">
                    {% for err in form.username.errors %}
                    <div class="col-md-12">
                        <a style="color:red">{{ err }}</a>
                    </div>
                    {% endfor %}
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.username }}
                    </div>
                </div>
                <div class="field">
                    {% for err in form.code.errors %}
                    <div class="col-md-12">
                        <a style="color:red">{{ err }}</a>
                    </div>
                    {% endfor %}
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.code }}
                    </div>
                </div>
                <div class="field">
                    {% for err in form.email.errors %}
                    <div class="col-md-12">
                        <a style="color:red">{{ err }}</a>
                    </div>
                    {% endfor %}
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.email }}
                    </div>
                </div>
                <div class="field">
                    {% for err in form.pwd.errors %}
                    <div class="col-md-12">
                        <a style="color:red">{{ err }}</a>
                    </div>
                    {% endfor %}
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.pwd }}
                    </div>
                </div>
                <div class="field">
                    {% for err in form.pwd2.errors %}
                    <div class="col-md-12">
                        <a style="color:red">{{ err }}</a>
                    </div>
                    {% endfor %}
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.pwd2 }}
                        {{ form.csrf_token }}
                    </div>
                </div>
                <button class="ui fluid large teal submit button" type="submit">注册</button>
            </div>
            <div class="ui middle aligned center aligned grid">
                <div class="ui stacked segment">
                    <h3 style="color: #16A085;">注册码获取方式</h3>
                    <a href="/zfbzf/">1.1支付宝</a>
                    <br>
                    <a href="/wxzf/">1.2微信</a>
                    <br>
                    <a href="/wxfriend/">2.加微信并且发送付款账单截图</a>
                    <br>
                    <a>3.正常时间会回复注册码(9:00 ~ 24:00)</a>
                    <br>
                    <a><b>诚信！</b></a>
                    <a><b>骗你司马！</b></a>

                </div>
            </div>

        </form>
    </div>
</div>
{% endblock %}

app/templates/home/upload.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Upload</title>
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/upload.css">
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/video.css">
    <link rel="icon" href="http://127.0.0.1:8080/favicon.png" type="image/png">
</head>

<body>
  <h4 align="center" class="heading2">Upload video</h4>
  <form action="upload" method="POST" enctype=multipart/form-data>
    <input type="file" accept="video/mp4" name=file>
    <p>Drag your files here or click in this area.</p>
    <input type="text" name="title" id="title" placeholder="Enter title here" required>
    <button type="submit">Upload</button>
  </form>
  <script src='http://127.0.0.1:8080/js/jquery.js'></script>
  <script  src="http://127.0.0.1:8080/js/upload.js"></script>
</body>
</html>

app/templates/home/user_dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/bootstrap-min-337.css">
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/user_list.css">
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/home.css">
    <link rel="stylesheet" href="http://127.0.0.1:8080/css/dashboard.css">
    <link rel="icon" href="http://127.0.0.1:8080/favicon.png" type="image/png">
  </head>
  <body class="back">
    <nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="container-fluid">
       <div class="navbar-header">
         <a style="color: #16A085;" class="navbar-brand" href="{{ url_for('start') }}">VideoHub</a>
       </div>
       <form class="ml navbar-form navbar-left" action="search" method="post">
          <div class="form-group">
            <input style="width:500px" name="search" type="text" class="form-control" placeholder="Search">
          </div>
          <button style="background-color:#16A085" type="submit" class="bt btn btn-default">Submit</button>
       </form>
       <ul class="nav navbar-nav navbar-right">
         <li><a style="color: #16A085;" href="{{ url_for('random_video') }}">Random</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('favourites') }}">Favourites</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('upload_form') }}">Upload</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('my_videos') }}">My videos</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('watched_videos') }}">Watched</a></li>
         <li><a style="color: #16A085;" href="{{ url_for('logout_user') }}">Logout</a></li>
     </ul>
     </div>
    </nav>
    <br><br><br><br><br>
    <div class="wrapper">
    <div style="text-align:center">
      <a style="text-decoration:none;" href="{{ url_for('password_update_form') }}" class="buttonDash">Change Password</a>
      <br><br><br><br>
      <a style="text-decoration:none;" href="{{ url_for('delete_own_account') }}" class="buttonDash">Delete Account</a>
    </div>
    </div>
    <br><br><br>
    <h2 style="color:#16A085; text-align:center;">{{ username }}'s statistics</h2>
    <br><br>
    <div class="table-responsive-vertical shadow-z-1">
    <table id="table" class="table table-hover">
        <tbody>
          <tr>
            <td style="color:#FFFFFF;" data-title="video_count">Total number of videos uploaded</td>
            <td style="color:#FFFFFF;" data-title="count">{{ video_count }}</td>
          </tr>
          <tr>
            <td style="color:#FFFFFF;" data-title="view_count">Total number of views</td>
            <td style="color:#FFFFFF;" data-title="v_count">{{ view_count }}</td>
          </tr>
          <tr>
            <td style="color:#FFFFFF;" data-title="best_vid">Video with highest views</td>
            <td style="color:#FFFFFF;" data-title="v_count"><a style="color:#16A085;text-decoration:none;" href="{{ url_for('watch_video', v = high_video_ID) }}">{{ high_title }}</a></td>
          </tr>
          <tr>
            <td style="color:#FFFFFF;" data-title="best_vid">Favourite video</td>
            <td style="color:#FFFFFF;" data-title="v_count"><a style="color:#16A085;text-decoration:none;" href="{{ url_for('watch_video', v = fav_video_ID) }}">{{ fav_title }}</a></td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/templates/home/user_list.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>User List - VideoHub</title>
  <link rel="stylesheet" href="http://127.0.0.1:8080/css/bootstrap-min-337.css">
  <link rel="stylesheet" href="http://127.0.0.1:8080/css/user_list.css">
  <link rel="icon" href="http://127.0.0.1:8080/favicon.png" type="image/png">
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="navbar-header">
       <a style="color: #16A085;" class="navbar-brand" href="{{ url_for('start') }}">VideoHub</a>
     </div>
     <ul class="nav navbar-nav navbar-right">
       <li><a style="color: #16A085;" href="{{ url_for('dashboard') }}">Dashboard</a></li>
       <li><a style="color: #16A085;" href="{{ url_for('add_admin') }}">Add Administrator</a></li>
       <li><a style="color: #16A085;" href="{{ url_for('flagged_videos') }}">Flagged Videos</a></li>
       <li><a style="color: #16A085;" href="{{ url_for('logout_user') }}">Logout</a></li>
   </ul>
  </nav>
  <div id="demo"><br><br>
  <h1>List of users</h1>
  <br><br>
  <div class="table-responsive-vertical shadow-z-1">
  <table id="table" class="table table-hover">
      <thead>
        <tr>
          <th>Username</th>
          <th>Number of videos</th>
          <th>Number of flagged videos</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for username in user_dict %}
        <tr>
          <td style="color:#FFFFFF;" data-title="Username">{{ username }}</td>
          <td style="color:#FFFFFF;" data-title="Number of videos">{{ user_dict[username][0] }}</td>
          <td style="color:#FFFFFF;" data-title="Number of flagged videos">{{ user_dict[username][1] }}</td>
          <td style="color:#FFFFFF;" data-title="Delete"><a style="color:#16A085;text-decoration:none;" href="/admin-delete-user/{{ username }}">Delete</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</body>
</html>

app/templates/home/video.html
{% extends "home/home.html" %}
{% block content %}

<br><br><br>
<br><br><br>
<h1 align="center" class="heading1">{{ title }}</h1>
<video class="center" controls autoplay style="position:center;">
    <source src="http://127.0.0.1:8080/video/{{ video_ID }}" type="video/mp4">
    Your broswer doesn't support this format.
</video>
<br>
<p style="text-align:center; color:#FFFFFF; font-size:22px;">Uploaded by <a
        style="color:#16A085; font-size:22px; text-decoration:none;" href="/user/{{ uploader }}">{{ uploader }}</a></p>
<br>
<p style="text-align:center; color:#FFFFFF; font-size:19px;">Uploaded on {{ vid_upload_date }}</p>
<br>
{% if views == "1" %}
<p style="text-align:center; color:#FFFFFF; font-size:19px;">{{ views }} view</p>
{% endif %}
{% if views != "1" %}
<p style="text-align:center; color:#FFFFFF; font-size:19px;">{{ views }} views</p>
{% endif %}
{% if logged_in %}
{% if not username == uploader %}
<br>
<div style="text-align: center;">
    <a style="font-size: 18px; color:#16A085; text-decoration: none;" href="{{ url_for('flag_video', v = video_ID) }}">Flag
        video</a>
</div>
{% endif %}
{% endif %}
<br><br><br>
<p style="padding-left:175px; color:#FFFFFF; font-size:25px;">More videos to watch</p><br>
<div class="container">
    {% for i in random_vids %}
    <div class="row">
        <div class="row">
            <div class="col-xs-12 col-sm-3 col-md-3">
                <a href="{{ url_for('watch_video', v = i) }}">
                    <img height="152" width="270" src="http://127.0.0.1:8080/image/{{ i }}" class="img-responsive">
                </a>
            </div>
            <h4><a style="color:#16A085;text-decoration:none;" href="{{ url_for('watch_video', v = i) }}">{{
                random_vids[i][0] }}</a></h4>
            <div class="col-xs-12 col-sm-9 col-md-9">
                <div class="list-group">
                    <div class="list-group-item">
                        <div class="row-content">
                            <div class="list-group-item-heading">
                                <p style="color:#FFFFFF;">
                                    {% if random_vids[i][1] == "1" %}
                                    <small>{{ random_vids[i][1] }} view</small>
                                    {% endif %}
                                    {% if random_vids[i][1] != "1" %}
                                    <small>{{ random_vids[i][1] }} views</small>
                                    {% endif %}
                                </p>
                            </div>
                            <div class="list-group-item-heading">
                                <p style="color:#FFFFFF;">
                                    <small>Uploaded by <a style="color:#16A085;text-decoration:none;"
                                                          href="/user/{{ random_vids[i][2] }}">{{ random_vids[i][2]
                                        }}</a></small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/home/zfbzf.html
{% extends "home/home.html" %}
{% block content %}
<br>
<br>
<div align="center">
    <img src="{{ url_for('static',filename='img/zfbzf.jpg') }}" width="300px" height="400px">
</div>
{% endblock %}